name: Release
permissions:
  contents: write

on:
  release:
    types: [ created ]

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        os: [ linux, windows ]
        arch: [ amd64 ]
    name: Release - ${{matrix.os}}-${{matrix.arch}}
    runs-on: ubuntu-24.04
    env:
      GOOS: ${{matrix.os}}
      GOARCH: ${{matrix.arch}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Setup MinGW
        if: ${{ env.GOOS == 'windows' }}
        run: |
          sudo apt install g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CC=/usr/bin/x86_64-w64-mingw32-gcc" >> $GITHUB_ENV

      - name: compile
        id: compile
        run: | 
          make
          echo "binary=$(find build -type f | head -1)" >> "$GITHUB_OUTPUT"

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: laravel-ls-${{github.event.release.tag_name}}-${{matrix.os}}-${{matrix.arch}}
          asset_path: ${{ steps.compile.outputs.binary }}
          asset_content_type: application/octal-stream

